// <auto-generated />
using System;
using GeneralSettings.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeneralSettings.Data.Migrations
{
    [DbContext(typeof(GeneralSettingsDbContext))]
    [Migration("20260621142013_HomePageTemplates")]
    partial class HomePageTemplates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("GeneralSettings")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GeneralSettings.GeneralSettings.Models.CompanySetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DefaultLatitude")
                        .HasColumnType("float");

                    b.Property<string>("DefaultLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DefaultLongitude")
                        .HasColumnType("float");

                    b.Property<Guid?>("DefaultPosCustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CompanySettings", "GeneralSettings");
                });

            modelBuilder.Entity("GeneralSettings.GeneralSettings.Models.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Currencies", "GeneralSettings");
                });

            modelBuilder.Entity("GeneralSettings.GeneralSettings.Models.HomePageTemplateContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AltTextAr")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("AltTextEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("TextAr")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("TextEn")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("GeneralSettings.GeneralSettings.Models.HomePageTemplateSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActiveTemplateKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("HomePageTemplateSelections", "GeneralSettings");
                });

            modelBuilder.Entity("GeneralSettings.GeneralSettings.Models.CampaignLandingHomePageContent", b =>
                {
                    b.HasBaseType("GeneralSettings.GeneralSettings.Models.HomePageTemplateContent");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyId", "SectionKey", "FieldKey")
                        .IsUnique();

                    b.ToTable("CampaignLandingHomePageContents", "GeneralSettings");
                });

            modelBuilder.Entity("GeneralSettings.GeneralSettings.Models.CorporateShowcaseHomePageContent", b =>
                {
                    b.HasBaseType("GeneralSettings.GeneralSettings.Models.HomePageTemplateContent");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyId", "SectionKey", "FieldKey")
                        .IsUnique();

                    b.ToTable("CorporateShowcaseHomePageContents", "GeneralSettings");
                });

            modelBuilder.Entity("GeneralSettings.GeneralSettings.Models.CurrentStorefrontHomePageContent", b =>
                {
                    b.HasBaseType("GeneralSettings.GeneralSettings.Models.HomePageTemplateContent");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyId", "SectionKey", "FieldKey")
                        .IsUnique();

                    b.ToTable("CurrentStorefrontHomePageContents", "GeneralSettings");
                });

            modelBuilder.Entity("GeneralSettings.GeneralSettings.Models.MinimalCatalogHomePageContent", b =>
                {
                    b.HasBaseType("GeneralSettings.GeneralSettings.Models.HomePageTemplateContent");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyId", "SectionKey", "FieldKey")
                        .IsUnique();

                    b.ToTable("MinimalCatalogHomePageContents", "GeneralSettings");
                });

            modelBuilder.Entity("GeneralSettings.GeneralSettings.Models.ProductHighlightHomePageContent", b =>
                {
                    b.HasBaseType("GeneralSettings.GeneralSettings.Models.HomePageTemplateContent");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyId", "SectionKey", "FieldKey")
                        .IsUnique();

                    b.ToTable("ProductHighlightHomePageContents", "GeneralSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
