// <auto-generated />
using System;
using GeneralSettings.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeneralSettings.Data.Migrations
{
    [DbContext(typeof(GeneralSettingsDbContext))]
    [Migration("20261008001222_AddPublicWebsiteManagedStorage")]
    partial class AddPublicWebsiteManagedStorage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("GeneralSettings")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GeneralSettings.GeneralSettings.Features.PublicWebsite.PublicWebsiteAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime2");

                    b.Property<string>("By")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Token")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "At");

                    b.ToTable("PublicWebsiteAudit", "GeneralSettings");
                });

            modelBuilder.Entity("GeneralSettings.GeneralSettings.Features.PublicWebsite.PublicWebsiteConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Activated")
                        .HasColumnType("bit");

                    b.Property<Guid>("AdministratorParentCompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ImageLimitMiB")
                        .HasColumnType("int");

                    b.Property<int>("MediaLimitMiB")
                        .HasColumnType("int");

                    b.Property<Guid>("OwnerCompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PdfLimitMiB")
                        .HasColumnType("int");

                    b.Property<string>("PublicOrigin")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("StorageLocationKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("Token")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("PublicWebsiteConfiguration", "GeneralSettings", t =>
                        {
                            t.HasCheckConstraint("CK_PublicWebsiteConfiguration_Singleton", "[Id] = 1");
                        });
                });

            modelBuilder.Entity("GeneralSettings.GeneralSettings.Features.PublicWebsite.PublicWebsiteManagedLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("ParentCompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RootKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ParentCompanyId", "RootKey", "FolderName")
                        .IsUnique();

                    b.ToTable("PublicWebsiteManagedLocations", "GeneralSettings");
                });

            modelBuilder.Entity("GeneralSettings.GeneralSettings.Features.PublicWebsite.PublicWebsiteMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("WasPublished")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("PublicWebsiteMedia", "GeneralSettings");
                });

            modelBuilder.Entity("GeneralSettings.GeneralSettings.Features.PublicWebsite.PublicWebsiteRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PublishedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "PublishedAt");

                    b.ToTable("PublicWebsiteRevisions", "GeneralSettings");
                });

            modelBuilder.Entity("GeneralSettings.GeneralSettings.Features.PublicWebsite.PublicWebsiteSite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DraftJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PublishedRevisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Token")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("PublicWebsiteSites", "GeneralSettings");
                });

            modelBuilder.Entity("GeneralSettings.GeneralSettings.Models.CompanySetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DefaultLatitude")
                        .HasColumnType("float");

                    b.Property<string>("DefaultLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DefaultLongitude")
                        .HasColumnType("float");

                    b.Property<Guid?>("DefaultPosCustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CompanySettings", "GeneralSettings");
                });

            modelBuilder.Entity("GeneralSettings.GeneralSettings.Models.CompanySetupProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentStepKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RemindersDismissed")
                        .HasColumnType("bit");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("int");

                    b.Property<string>("SelectedTrackKeys")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SkippedStepKeys")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("CompanySetupProfiles", "GeneralSettings");
                });

            modelBuilder.Entity("GeneralSettings.GeneralSettings.Models.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Currencies", "GeneralSettings");
                });

            modelBuilder.Entity("GeneralSettings.GeneralSettings.Models.HomePageTemplateContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AltTextAr")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("AltTextEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("TextAr")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("TextEn")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("GeneralSettings.GeneralSettings.Models.HomePageTemplateSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActiveTemplateKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("HomePageTemplateSelections", "GeneralSettings");
                });

            modelBuilder.Entity("GeneralSettings.GeneralSettings.Models.BoldEnergeticLandingHomePageContent", b =>
                {
                    b.HasBaseType("GeneralSettings.GeneralSettings.Models.HomePageTemplateContent");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyId", "SectionKey", "FieldKey")
                        .IsUnique();

                    b.ToTable("BoldEnergeticLandingHomePageContents", "GeneralSettings");
                });

            modelBuilder.Entity("GeneralSettings.GeneralSettings.Models.CorporateTrustLandingHomePageContent", b =>
                {
                    b.HasBaseType("GeneralSettings.GeneralSettings.Models.HomePageTemplateContent");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyId", "SectionKey", "FieldKey")
                        .IsUnique();

                    b.ToTable("CorporateTrustLandingHomePageContents", "GeneralSettings");
                });

            modelBuilder.Entity("GeneralSettings.GeneralSettings.Models.CurrentStorefrontHomePageContent", b =>
                {
                    b.HasBaseType("GeneralSettings.GeneralSettings.Models.HomePageTemplateContent");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyId", "SectionKey", "FieldKey")
                        .IsUnique();

                    b.ToTable("CurrentStorefrontHomePageContents", "GeneralSettings");
                });

            modelBuilder.Entity("GeneralSettings.GeneralSettings.Models.MinimalistLandingHomePageContent", b =>
                {
                    b.HasBaseType("GeneralSettings.GeneralSettings.Models.HomePageTemplateContent");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyId", "SectionKey", "FieldKey")
                        .IsUnique();

                    b.ToTable("MinimalistLandingHomePageContents", "GeneralSettings");
                });

            modelBuilder.Entity("GeneralSettings.GeneralSettings.Models.ModernDarkModeLandingHomePageContent", b =>
                {
                    b.HasBaseType("GeneralSettings.GeneralSettings.Models.HomePageTemplateContent");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyId", "SectionKey", "FieldKey")
                        .IsUnique();

                    b.ToTable("ModernDarkModeLandingHomePageContents", "GeneralSettings");
                });

            modelBuilder.Entity("GeneralSettings.GeneralSettings.Models.SoftSaasLandingHomePageContent", b =>
                {
                    b.HasBaseType("GeneralSettings.GeneralSettings.Models.HomePageTemplateContent");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyId", "SectionKey", "FieldKey")
                        .IsUnique();

                    b.ToTable("SoftSaasLandingHomePageContents", "GeneralSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
