<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Data\Configurations\" />
    <Folder Include="Data\Seed\" />
    <Folder Include="Orders\Features\ConfirmOrder\" />
    <Folder Include="Orders\Features\ChangeLIneQuantity\" />
    <Folder Include="Orders\Features\ChangeLInePrice\" />
    <Folder Include="Orders\Features\ChangeDiscountRate\" />
    <Folder Include="Orders\Features\ChangeTaxRate\" />
    <Folder Include="Orders\Features\RemoveLine\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\Shared\Shared.csproj" />
    <ProjectReference Include="..\..\Pricing\Pricing\Pricing.csproj" />
  </ItemGroup>

</Project>
