using AlAfkarERP.Shared.Dtos;
using SharedWithUI.Catering.Dtos;
using SharedWithUI.Catering.Enums;

namespace AlAfkarERP.Shared.Pages.Features.Catering.Services;

public interface ICateringService
{
    Task<ApiResult<CateringDashboardDto>> GetDashboardAsync(Guid? companyId = null);
    Task<ApiResult<PaginatedResult<MealDefinitionDto>>> GetMealsAsync(int pageIndex, int pageSize, Guid? companyId = null, string? searchText = null, bool activeOnly = true);
    Task<ApiResult<MealDefinitionDto>> GetMealByIdAsync(Guid id);
    Task<ApiResult<CreateResponseDto>> CreateMealAsync(MealDefinitionDto meal);
    Task<ApiResult<UpdateDeleteResponseDto>> UpdateMealAsync(MealDefinitionDto meal);
    Task<ApiResult<UpdateDeleteResponseDto>> DeleteMealAsync(Guid id);
    Task<ApiResult<CreateResponseDto>> AddMealComponentAsync(Guid mealId, MealComponentDto component);
    Task<ApiResult<UpdateDeleteResponseDto>> DeleteMealComponentAsync(Guid mealId, Guid componentId);
    Task<ApiResult<PaginatedResult<CateringContractDto>>> GetContractsAsync(int pageIndex, int pageSize, Guid? companyId = null, string? searchText = null, Guid? customerId = null, CateringContractStatus? status = null);
    Task<ApiResult<CateringContractDto>> GetContractByIdAsync(Guid id);
    Task<ApiResult<CreateResponseDto>> CreateContractAsync(CateringContractDto contract);
    Task<ApiResult<UpdateDeleteResponseDto>> UpdateContractAsync(CateringContractDto contract);
    Task<ApiResult<UpdateDeleteResponseDto>> DeleteContractAsync(Guid id);
    Task<ApiResult<UpdateDeleteResponseDto>> CloseContractAsync(Guid id);
    Task<ApiResult<CreateResponseDto>> AddAddendumAsync(Guid contractId, CateringContractAddendumDto addendum);
    Task<ApiResult<PaginatedResult<CateringAreaDto>>> GetAreasAsync(int pageIndex, int pageSize, Guid? companyId = null, string? searchText = null, bool activeOnly = true);
    Task<ApiResult<CreateResponseDto>> CreateAreaAsync(CateringAreaDto area);
    Task<ApiResult<UpdateDeleteResponseDto>> UpdateAreaAsync(CateringAreaDto area);
    Task<ApiResult<PaginatedResult<CateringSquareDto>>> GetSquaresAsync(int pageIndex, int pageSize, Guid? companyId = null, Guid? areaId = null, string? searchText = null, bool activeOnly = true);
    Task<ApiResult<CreateResponseDto>> CreateSquareAsync(CateringSquareDto square);
    Task<ApiResult<UpdateDeleteResponseDto>> UpdateSquareAsync(CateringSquareDto square);
    Task<ApiResult<PaginatedResult<CateringDailyScheduleDto>>> GetSchedulesAsync(int pageIndex, int pageSize, Guid? contractId = null, DateTime? fromDate = null, DateTime? toDate = null, Guid? projectId = null, Guid? projectDailyPlanId = null);
    Task<ApiResult<CreateResponseDto>> CreateScheduleAsync(CateringDailyScheduleDto schedule);
    Task<ApiResult<UpdateDeleteResponseDto>> UpdateScheduleAsync(CateringDailyScheduleDto schedule);
    Task<ApiResult<UpdateDeleteResponseDto>> ActivateScheduleAsync(Guid scheduleId);
    Task<ApiResult<CreateResponseDto>> CreateAllocationAsync(Guid scheduleId, CateringSquareAllocationDto allocation);
    Task<ApiResult<UpdateDeleteResponseDto>> RecordAllocationActualsAsync(Guid allocationId, decimal receivedQuantity, decimal distributedQuantity, DateTime? actualArrivalTime, Guid? receivingSupervisorEmployeeId, string? receivingSupervisorName, Guid? teamLeaderEmployeeId, string? teamLeaderName, string? varianceNotes);
    Task<ApiResult<PaginatedResult<CateringPackagingPlanDto>>> GetPackagingPlansAsync(int pageIndex, int pageSize, Guid? scheduleId = null, DateTime? fromDate = null, DateTime? toDate = null);
    Task<ApiResult<CreateResponseDto>> UpsertPackagingPlanAsync(CateringPackagingPlanDto packagingPlan);
    Task<ApiResult<UpdateDeleteResponseDto>> ReleasePackagingStockAsync(Guid packagingPlanId);
    Task<ApiResult<UpdateDeleteResponseDto>> StartPackagingAsync(Guid packagingPlanId);
    Task<ApiResult<UpdateDeleteResponseDto>> CompletePackagingAsync(Guid packagingPlanId, decimal preparedMealCount, decimal rejectedMealCount, decimal damagedMealCount, string? varianceReason);
    Task<ApiResult<PaginatedResult<CateringDispatchPlanDto>>> GetDispatchPlansAsync(int pageIndex, int pageSize, Guid? scheduleId = null, DateTime? fromDate = null, DateTime? toDate = null);
    Task<ApiResult<CreateResponseDto>> UpsertDispatchPlanAsync(CateringDispatchPlanDto dispatchPlan);
    Task<ApiResult<UpdateDeleteResponseDto>> CreateDispatchFleetAssignmentAsync(Guid dispatchPlanId);
    Task<ApiResult<UpdateDeleteResponseDto>> RecordExecutionEventAsync(CateringExecutionEventDto executionEvent);
    Task<ApiResult<PaginatedResult<CateringVehicleDeliveryDto>>> GetDeliveriesAsync(int pageIndex, int pageSize, Guid? scheduleId = null, DateTime? fromDate = null, DateTime? toDate = null);
    Task<ApiResult<CreateResponseDto>> CreateDeliveryAsync(CateringVehicleDeliveryDto delivery);
    Task<ApiResult<PaginatedResult<CateringAssignmentDto>>> GetAssignmentsAsync(int pageIndex, int pageSize, Guid? contractId = null, CateringAssignmentRole? role = null, Guid? squareId = null);
    Task<ApiResult<CreateResponseDto>> CreateAssignmentAsync(CateringAssignmentDto assignment);
    Task<ApiResult<UpdateDeleteResponseDto>> UpdateAssignmentAsync(CateringAssignmentDto assignment);
    Task<ApiResult<UpdateDeleteResponseDto>> DeleteAssignmentAsync(Guid id);
    Task<ApiResult<PaginatedResult<CateringProjectDto>>> GetProjectsAsync(int pageIndex, int pageSize, Guid? companyId = null, Guid? contractId = null);
    Task<ApiResult<CateringProjectDto>> GetProjectByIdAsync(Guid id);
    Task<ApiResult<CreateResponseDto>> CreateProjectAsync(CateringProjectDto project);
    Task<ApiResult<UpdateDeleteResponseDto>> UpdateProjectAsync(CateringProjectDto project);
    Task<ApiResult<UpdateDeleteResponseDto>> DeleteProjectAsync(Guid id);
    Task<ApiResult<CreateResponseDto>> UpsertProjectDailyPlanAsync(CateringProjectDailyPlanDto dailyPlan);
    Task<ApiResult<CateringGenerateDailyPlanResultDto>> GenerateProjectDailyPlansAsync(CateringGenerateProjectDailyPlansRequestDto request);
    Task<ApiResult<PaginatedResult<CateringOperationalPlanDto>>> GetPlansAsync(int pageIndex, int pageSize, Guid? companyId = null, Guid? contractId = null);
    Task<ApiResult<CreateResponseDto>> CreatePlanAsync(CateringOperationalPlanDto plan);
    Task<ApiResult<UpdateDeleteResponseDto>> UpdatePlanAsync(CateringOperationalPlanDto plan);
    Task<ApiResult<UpdateDeleteResponseDto>> DeletePlanAsync(Guid id);
    Task<ApiResult<CreateResponseDto>> AddPlanResourceAsync(Guid planId, CateringPlanResourceAssignmentDto resource);
    Task<ApiResult<UpdateDeleteResponseDto>> DeletePlanResourceAsync(Guid planId, Guid resourceId);
    Task<ApiResult<CateringGenerateDailyPlanResultDto>> GenerateDailyPlansAsync(CateringGenerateDailyPlanRequestDto request);
    Task<ApiResult<PaginatedResult<CateringInventoryRequestDto>>> GetInventoryRequestsAsync(int pageIndex, int pageSize, Guid? companyId = null, Guid? planId = null, Guid? scheduleId = null, CateringInventoryRequestStatus? status = null);
    Task<ApiResult<CreateResponseDto>> CreateInventoryRequestAsync(CateringInventoryRequestDto request);
    Task<ApiResult<UpdateDeleteResponseDto>> SubmitInventoryRequestAsync(Guid id);
    Task<ApiResult<UpdateDeleteResponseDto>> ApproveInventoryRequestAsync(Guid id);
    Task<ApiResult<UpdateDeleteResponseDto>> FulfillInventoryRequestAsync(Guid id);
    Task<ApiResult<List<CateringReportRowDto>>> GetOperationsReportAsync(Guid? companyId = null, Guid? contractId = null, DateTime? fromDate = null, DateTime? toDate = null);
}
