<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DefaultItemExcludes>$(DefaultItemExcludes);artifacts\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="GeneralSettings/Dtos/PublicWebsite.manifest.json" LogicalName="SharedWithUI.PublicWebsite.manifest.json" />
  </ItemGroup>
</Project>
