<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\Shared.Contracts\Shared.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Shared\Shared\Shared.csproj" />
    <ProjectReference Include="..\..\Catalog\Catalog.Contracts\Catalog.Contracts.csproj" />
    <ProjectReference Include="..\Inventory.Contracts\Inventory.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Warehouses\Features\Inventories\zNew\InventoryAdjustment\" />
    <Folder Include="Warehouses\Features\Inventories\zNew\InventoryQueries\CurrentStock\" />
    <Folder Include="Warehouses\Features\Inventories\zNew\InventoryQueries\ExpiringBatches\" />
    <Folder Include="Warehouses\Features\Inventories\zNew\InventoryQueries\ProductAvailability\" />
    <Folder Include="Warehouses\Features\Inventories\zNew\InventoryQueries\StockByWarehouse\" />
    <Folder Include="Warehouses\Features\Inventories\zNew\ReleaseReservation\" />
    <Folder Include="Warehouses\Features\Inventories\zNew\ReserveStock\" />
    <Folder Include="Warehouses\Features\Inventories\zNew\StockOut\" />
    <Folder Include="Warehouses\Features\Inventories\zNew\StockIn\" />
    <Folder Include="Warehouses\Features\Inventories\zOld\TransferOut\" />
    <Folder Include="Warehouses\Features\Inventories\zOld\TransferIn\" />
    <Folder Include="Warehouses\Features\Inventories\zNew\OpeningStock\" />
    <Folder Include="Warehouses\Features\StockMovement\GetMovements\" />
    <Folder Include="Warehouses\Features\StockMovement\GetMovementDetails\" />
    <Folder Include="Warehouses\Features\WarehouseTransfers\CreateTransfer\" />
    <Folder Include="Warehouses\Features\WarehouseTransfers\AddTransferItem\" />
    <Folder Include="Warehouses\Features\WarehouseTransfers\CancelTransfer\" />
    <Folder Include="Warehouses\Features\WarehouseTransfers\GetTransfer\" />
    <Folder Include="Warehouses\Features\WarehouseTransfers\ListTransfers\" />
    <Folder Include="Warehouses\Features\WarehouseTransfers\ReceiveTransfer\" />
    <Folder Include="Warehouses\Features\WarehouseTransfers\ShipTransfer\" />
    <Folder Include="Warehouses\Features\WarehouseTransfers\RemoveTransferItem\" />
    <Folder Include="Warehouses\ValueObjects\" />
  </ItemGroup>

</Project>
